import React from "react";
import { useState } from "react";
import Head from "next/head";
import styles from "../modules/index.module.css";
import {getUser} from '../actions/getUser.js';

export default function Home() {
  const [input, setInput] = useState({
    username: "",
    password: "",
  });
  const [error, setError] = useState("");
  const [button, setButton] = useState({complete:false})

  function handleChange(e) {
    setInput({
      ...input,
      [e.target.name]: e.target.value,
    });

    setError(
      validate({
        ...input,
        [e.target.name]: e.target.value,
      })
    );
    console.log(input)
  }

  function validate(input) {
    let errors = {};
    if (!input.username) {
      errors.username = "El campo no puede quedar vacio";
    }
    if (!input.password) {
      errors.password = "El campo no puede quedar vacio";
    }
    
    if(errors.username || errors.password){
      setButton({
        complete:false
      })
    }else{
      setButton({
        complete:true
    })
    
  }
  return errors;
}

  function onHandleSubmit(e){
    e.preventDefault(e);
    console.log("username", input.username)
    console.log("password", input.password)
    let user = getUser(input);
    if(user.id){
      history.push("/ticket")
    }else{
      console.log("error")
    }
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.indexContainer}>
      <form className={styles.indexForm} onSubmit={ (e) => onHandleSubmit(e)}>
      
        <label className={styles.indexLabel}>Nombre de Usuario</label>
        <input
          type="text"
          name="username"
          value={input.username}
          onChange={(e) => handleChange(e)}
        />
        <p className={error.username ? `${styles.danger}` : `${styles.normal}`}>
          {error.username}
        </p>
        <label className={styles.indexLabel}>Contraseña</label>
        <input
          type="password"
          name="password"
          value={input.password}
          onChange={(e) => handleChange(e)}
        />
        <p className={error.password ? `${styles.danger}` : `${styles.normal}`}>
          {error.password}
        </p>
        {button.complete === false ? <button type="submit" disabled className={styles.indexButton}>Ingresar</button> : <button type="submit" className={styles.indexButton} >Ingresar</button>}
        
      </form>
      </div>
      
    </>
  );
}
