import React from "react";
import Navbar from "./Navbar";
import Head from "next/head";
import styles from '../modules/Layout.module.css'

const Layout = ({ children }) => {
  return (
    <>
      <Head>
        <title>Soportes Basani</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div className={styles.mainContainer}>
      <Navbar />
      <main className={styles.childrenContainer}>{children}</main>
    </div>
  </>
  );
};
export default Layout;